services = {
    # Social Media
    "Facebook": {"sender": "security@facebookmail.com", "file": "facebook_accounts.txt"},
    "Instagram": {"sender": "security@mail.instagram.com", "file": "instagram_accounts.txt"},
    "TikTok": {"sender": "register@account.tiktok.com", "file": "tiktok_accounts.txt"},
    "Twitter": {"sender": "info@x.com", "file": "twitter_accounts.txt"},
    "LinkedIn": {"sender": "security-noreply@linkedin.com", "file": "linkedin_accounts.txt"},
    "Pinterest": {"sender": "no-reply@pinterest.com", "file": "pinterest_accounts.txt"},
    "Reddit": {"sender": "noreply@reddit.com", "file": "reddit_accounts.txt"},
    "Snapchat": {"sender": "no-reply@accounts.snapchat.com", "file": "snapchat_accounts.txt"},
    "VK": {"sender": "noreply@vk.com", "file": "vk_accounts.txt"},
    "WeChat": {"sender": "no-reply@wechat.com", "file": "wechat_accounts.txt"},
    
    # Messaging
    "WhatsApp": {"sender": "no-reply@whatsapp.com", "file": "whatsapp_accounts.txt"},
    "Telegram": {"sender": "telegram.org", "file": "telegram_accounts.txt"},
    "Discord": {"sender": "noreply@discord.com", "file": "discord_accounts.txt"},
    "Signal": {"sender": "no-reply@signal.org", "file": "signal_accounts.txt"},
    "Line": {"sender": "no-reply@line.me", "file": "line_accounts.txt"},
    
    # Streaming & Entertainment
    "Netflix": {"sender": "info@account.netflix.com", "file": "netflix_accounts.txt"},
    "Spotify": {"sender": "no-reply@spotify.com", "file": "spotify_accounts.txt"},
    "Twitch": {"sender": "no-reply@twitch.tv", "file": "twitch_accounts.txt"},
    "YouTube": {"sender": "no-reply@youtube.com", "file": "youtube_accounts.txt"},
    "Vimeo": {"sender": "noreply@vimeo.com", "file": "vimeo_accounts.txt"},
    "Disney+": {"sender": "no-reply@disneyplus.com", "file": "disneyplus_accounts.txt"},
    "Hulu": {"sender": "account@hulu.com", "file": "hulu_accounts.txt"},
    "HBO Max": {"sender": "no-reply@hbomax.com", "file": "hbomax_accounts.txt"},
    "Amazon Prime": {"sender": "auto-confirm@amazon.com", "file": "amazonprime_accounts.txt"},
    "Apple TV+": {"sender": "no-reply@apple.com", "file": "appletv_accounts.txt"},
    "Crunchyroll": {"sender": "noreply@crunchyroll.com", "file": "crunchyroll_accounts.txt"},
    
    # E-commerce & Shopping
    "Amazon": {"sender": "auto-confirm@amazon.com", "file": "amazon_accounts.txt"},
    "eBay": {"sender": "newuser@nuwelcome.ebay.com", "file": "ebay_accounts.txt"},
    "Shopify": {"sender": "no-reply@shopify.com", "file": "shopify_accounts.txt"},
    "Etsy": {"sender": "transaction@etsy.com", "file": "etsy_accounts.txt"},
    "AliExpress": {"sender": "no-reply@aliexpress.com", "file": "aliexpress_accounts.txt"},
    "Walmart": {"sender": "no-reply@walmart.com", "file": "walmart_accounts.txt"},
    "Target": {"sender": "no-reply@target.com", "file": "target_accounts.txt"},
    "Best Buy": {"sender": "no-reply@bestbuy.com", "file": "bestbuy_accounts.txt"},
    "Newegg": {"sender": "no-reply@newegg.com", "file": "newegg_accounts.txt"},
    "Wish": {"sender": "no-reply@wish.com", "file": "wish_accounts.txt"},
    
    # Payment & Finance
    "PayPal": {"sender": "service@paypal.com.br", "file": "paypal_accounts.txt"},
    "Binance": {"sender": "do-not-reply@ses.binance.com", "file": "binance_accounts.txt"},
    "Coinbase": {"sender": "no-reply@coinbase.com", "file": "coinbase_accounts.txt"},
    "Kraken": {"sender": "no-reply@kraken.com", "file": "kraken_accounts.txt"},
    "Bitfinex": {"sender": "no-reply@bitfinex.com", "file": "bitfinex_accounts.txt"},
    "OKX": {"sender": "noreply@okx.com", "file": "okx_accounts.txt"},
    "Bybit": {"sender": "no-reply@bybit.com", "file": "bybit_accounts.txt"},
    "Bitkub": {"sender": "no-reply@bitkub.com", "file": "bitkub_accounts.txt"},
    "Revolut": {"sender": "no-reply@revolut.com", "file": "revolut_accounts.txt"},
    "TransferWise": {"sender": "no-reply@transferwise.com", "file": "transferwise_accounts.txt"},
    "Venmo": {"sender": "no-reply@venmo.com", "file": "venmo_accounts.txt"},
    "Cash App": {"sender": "no-reply@cash.app", "file": "cashapp_accounts.txt"},
    
    # Gaming Platforms
    "Steam": {"sender": "noreply@steampowered.com", "file": "steam_accounts.txt"},
    "Xbox": {"sender": "xboxreps@engage.xbox.com", "file": "xbox_accounts.txt"},
    "PlayStation": {"sender": "reply@txn-email.playstation.com", "file": "playstation_accounts.txt"},
    "EpicGames": {"sender": "help@acct.epicgames.com", "file": "epicgames_accounts.txt"},
    "Rockstar": {"sender": "noreply@rockstargames.com", "file": "rockstar_accounts.txt"},
    "EA Sports": {"sender": "EA@e.ea.com", "file": "easports_accounts.txt"},
    "Ubisoft": {"sender": "noreply@ubisoft.com", "file": "ubisoft_accounts.txt"},
    "Blizzard": {"sender": "noreply@blizzard.com", "file": "blizzard_accounts.txt"},
    "Riot Games": {"sender": "no-reply@riotgames.com", "file": "riotgames_accounts.txt"},
    "Valorant": {"sender": "noreply@valorant.com", "file": "valorant_accounts.txt"},
    "Genshin Impact": {"sender": "noreply@hoyoverse.com", "file": "genshin_accounts.txt"},
    "PUBG": {"sender": "noreply@pubgmobile.com", "file": "pubg_accounts.txt"},
    "Free Fire": {"sender": "noreply@freefire.com", "file": "freefire_accounts.txt"},
    "Mobile Legends": {"sender": "noreply@mobilelegends.com", "file": "mobilelegends_accounts.txt"},
    "Call of Duty": {"sender": "noreply@callofduty.com", "file": "cod_accounts.txt"},
    "Fortnite": {"sender": "noreply@epicgames.com", "file": "fortnite_accounts.txt"},
    "Roblox": {"sender": "accounts@roblox.com", "file": "roblox_accounts.txt"},
    "Minecraft": {"sender": "noreply@mojang.com", "file": "minecraft_accounts.txt"},
    "Supercell": {"sender": "noreply@id.supercell.com", "file": "supercell_accounts.txt"},
    "Nintendo": {"sender": "no-reply@accounts.nintendo.com", "file": "nintendo_accounts.txt"},
}